server:
  port: 8081
spring:
  application:
    name: test-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
