server:
  port: 8080
spring:
  application:
    name: test-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    fetch-registry: false
    register-with-eureka: false
